import type { Company, Conversation, Order, Product, Trace } from './types';

/** Fictional restaurant fixtures for local demo mode. Never sent to live integrations. */
const date = '2026-09-09T13:30:00.000Z';
const first = '11111111-1111-4111-a111-111111111111';
const second = '22222222-2222-4222-a222-222222222222';
const pid = (n: number) => `33333333-3333-4333-a333-${String(n).padStart(12, '0')}`;
const oid = (n: number) => `44444444-4444-4444-a444-${String(n).padStart(12, '0')}`;
const cid = (n: number) => `55555555-5555-4555-a555-${String(n).padStart(12, '0')}`;
const opt = (n: number) => `66666666-6666-4666-a666-${String(n).padStart(12, '0')}`;

export const seedCompanies: Company[] = [
  {
    id: first,
    name: 'Dastarkhwan',
    slug: 'dastarkhwan',
    address: 'Demo restaurant · Gulberg III, Lahore',
    phone: '+92 300 000 0001',
    timezone: 'Asia/Karachi',
    currency: 'PKR',
    botEnabled: true,
    catalogSource: 'app',
    openingHours: { start: '00:00', end: '00:00', days: [0, 1, 2, 3, 4, 5, 6] },
    deliveryZones: [
      { name: 'Gulberg', fee: 15000 },
      { name: 'Model Town', fee: 20000 },
      { name: 'DHA', fee: 25000 },
    ],
    faqs: [
      {
        question: 'hours',
        answer:
          'This demo restaurant is open all day for testing. You can configure real opening hours in Settings.',
      },
      { question: 'payment', answer: 'We accept cash at pickup or on delivery.' },
      {
        question: 'allergy',
        answer:
          'Please speak with staff about allergies before ordering. Send “staff” to pause the bot and ask for help.',
      },
    ],
    ai: { provider: 'mock', model: 'demo-rules', keyMode: 'platform', monthlyBudgetUsd: 10 },
    createdAt: date,
  },
  {
    id: second,
    name: 'Bun & Co.',
    slug: 'bun-and-co',
    address: 'Demo restaurant · F-7 Markaz, Islamabad',
    phone: '+92 300 000 0002',
    timezone: 'Asia/Karachi',
    currency: 'PKR',
    botEnabled: true,
    catalogSource: 'app',
    openingHours: { start: '00:00', end: '00:00', days: [0, 1, 2, 3, 4, 5, 6] },
    deliveryZones: [
      { name: 'F-7', fee: 12000 },
      { name: 'F-6', fee: 15000 },
      { name: 'Blue Area', fee: 18000 },
    ],
    faqs: [
      { question: 'hours', answer: 'This demo restaurant is open all day for testing.' },
      { question: 'payment', answer: 'Cash payment is available at pickup or on delivery.' },
    ],
    ai: { provider: 'mock', model: 'demo-rules', keyMode: 'own', monthlyBudgetUsd: 10 },
    createdAt: date,
  },
];

export const seedProducts: Product[] = [
  {
    id: pid(1),
    companyId: first,
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice, tender chicken, and our house spice blend.',
    category: 'Rice & Biryani',
    price: 45000,
    available: true,
    emoji: '🍛',
    aliases: ['biryani', 'chicken biryani', 'بریانی', 'چکن بریانی'],
    variants: [],
    modifiers: [
      { id: opt(1), name: 'Extra raita', price: 8000 },
      { id: opt(2), name: 'Extra chicken', price: 18000 },
    ],
  },
  {
    id: pid(2),
    companyId: first,
    name: 'Chicken Karahi',
    description: 'Tomato, ginger, green chillies, and chicken cooked in a traditional karahi.',
    category: 'Karahi & Handi',
    price: 120000,
    available: true,
    emoji: '🥘',
    aliases: ['karahi', 'chicken karahi', 'کڑاہی', 'چکن کڑاہی'],
    variants: [
      { id: opt(3), name: 'Half', price: 120000 },
      { id: opt(4), name: 'Full', price: 220000 },
    ],
    modifiers: [{ id: opt(5), name: 'Extra butter', price: 10000 }],
  },
  {
    id: pid(3),
    companyId: first,
    name: 'Beef Seekh Kebab',
    description: 'Two charcoal-grilled skewers served with mint chutney.',
    category: 'BBQ',
    price: 58000,
    available: true,
    emoji: '🍢',
    aliases: ['seekh kebab', 'kebab', 'kabab', 'beef seekh kebab', 'سیخ کباب', 'کباب'],
    variants: [],
    modifiers: [{ id: opt(6), name: 'Extra chutney', price: 5000 }],
  },
  {
    id: pid(4),
    companyId: first,
    name: 'Chicken Tikka',
    description: 'A smoky, spiced chicken quarter fresh from the grill.',
    category: 'BBQ',
    price: 42000,
    available: true,
    emoji: '🍗',
    aliases: ['tikka', 'chicken tikka', 'تکہ', 'چکن تکہ'],
    variants: [],
    modifiers: [],
  },
  {
    id: pid(5),
    companyId: first,
    name: 'Butter Naan',
    description: 'Soft tandoor-baked bread brushed with butter.',
    category: 'Breads & Sides',
    price: 10000,
    available: true,
    emoji: '🫓',
    aliases: ['naan', 'butter naan', 'نان', 'بٹر نان'],
    variants: [],
    modifiers: [],
  },
  {
    id: pid(6),
    companyId: first,
    name: 'Daal Makhani',
    description: 'Slow-cooked black lentils finished with cream and butter.',
    category: 'Karahi & Handi',
    price: 48000,
    available: false,
    emoji: '🫘',
    aliases: ['daal', 'dal', 'daal makhani', 'دال', 'دال مکھنی'],
    variants: [],
    modifiers: [],
  },
  {
    id: pid(7),
    companyId: first,
    name: 'Mango Lassi',
    description: 'Chilled yogurt and mango, blended until smooth.',
    category: 'Drinks',
    price: 28000,
    available: true,
    emoji: '🥭',
    aliases: ['lassi', 'mango lassi', 'لسی', 'مینگو لسی'],
    variants: [],
    modifiers: [],
  },
  {
    id: pid(8),
    companyId: first,
    name: 'Gulab Jamun',
    description: 'Two warm milk dumplings in cardamom syrup.',
    category: 'Desserts',
    price: 22000,
    available: true,
    emoji: '🍮',
    aliases: ['gulab jamun', 'jamun', 'گلاب جامن'],
    variants: [],
    modifiers: [],
  },
  {
    id: pid(9),
    companyId: second,
    name: 'Classic Smash',
    description: 'Smashed beef patty, American cheese, pickles, and house sauce.',
    category: 'Burgers',
    price: 69000,
    available: true,
    emoji: '🍔',
    aliases: ['classic smash', 'smash burger', 'burger', 'برگر'],
    variants: [
      { id: opt(7), name: 'Single', price: 69000 },
      { id: opt(8), name: 'Double', price: 99000 },
    ],
    modifiers: [
      { id: opt(9), name: 'Extra cheese', price: 10000 },
      { id: opt(10), name: 'Jalapenos', price: 8000 },
    ],
  },
  {
    id: pid(10),
    companyId: second,
    name: 'Crispy Chicken',
    description: 'Crispy chicken fillet, crunchy slaw, and pepper mayo.',
    category: 'Burgers',
    price: 62000,
    available: true,
    emoji: '🥪',
    aliases: ['crispy chicken', 'chicken burger', 'چکن برگر'],
    variants: [],
    modifiers: [{ id: opt(11), name: 'Extra cheese', price: 10000 }],
  },
  {
    id: pid(11),
    companyId: second,
    name: 'Loaded Fries',
    description: 'Golden fries with cheese sauce and spring onions.',
    category: 'Sides',
    price: 39000,
    available: true,
    emoji: '🍟',
    aliases: ['loaded fries', 'fries', 'فرائز'],
    variants: [],
    modifiers: [{ id: opt(12), name: 'Extra cheese sauce', price: 8000 }],
  },
  {
    id: pid(12),
    companyId: second,
    name: 'Lemon Mint',
    description: 'Fresh lemon and mint over crushed ice.',
    category: 'Drinks',
    price: 25000,
    available: true,
    emoji: '🍋',
    aliases: ['lemon mint', 'mint lemonade', 'لیموں'],
    variants: [],
    modifiers: [],
  },
  {
    id: pid(13),
    companyId: second,
    name: 'Chocolate Brownie',
    description: 'A rich, warm chocolate brownie.',
    category: 'Desserts',
    price: 32000,
    available: false,
    emoji: '🍫',
    aliases: ['brownie', 'chocolate brownie', 'براؤنی'],
    variants: [],
    modifiers: [],
  },
];

export const seedOrders: Order[] = [
  {
    id: oid(1),
    companyId: first,
    conversationId: cid(1),
    reference: 'DEMO-1042',
    submissionKey: 'fixture:dastarkhwan:1042',
    customerName: 'Ali (demo)',
    customerPhone: '+92 300 000 0101',
    fulfillment: 'delivery',
    address: 'Demo address · House 12, Main Boulevard',
    zone: 'Gulberg',
    items: [
      {
        productId: pid(1),
        name: 'Chicken Biryani',
        quantity: 2,
        unitPrice: 45000,
        modifiers: [],
        notes: '',
        total: 90000,
      },
      {
        productId: pid(5),
        name: 'Butter Naan',
        quantity: 2,
        unitPrice: 10000,
        modifiers: [],
        notes: '',
        total: 20000,
      },
    ],
    subtotal: 110000,
    deliveryFee: 15000,
    total: 125000,
    currency: 'PKR',
    status: 'pending',
    syncStatus: 'not_connected',
    createdAt: '2026-09-09T13:25:00.000Z',
    updatedAt: date,
  },
  {
    id: oid(2),
    companyId: first,
    conversationId: cid(2),
    reference: 'DEMO-1041',
    submissionKey: 'fixture:dastarkhwan:1041',
    customerName: 'Sara (demo)',
    customerPhone: '+92 300 000 0102',
    fulfillment: 'pickup',
    items: [
      {
        productId: pid(4),
        name: 'Chicken Tikka',
        quantity: 2,
        unitPrice: 42000,
        modifiers: [],
        notes: '',
        total: 84000,
      },
      {
        productId: pid(7),
        name: 'Mango Lassi',
        quantity: 2,
        unitPrice: 28000,
        modifiers: [],
        notes: '',
        total: 56000,
      },
    ],
    subtotal: 140000,
    deliveryFee: 0,
    total: 140000,
    currency: 'PKR',
    status: 'preparing',
    syncStatus: 'not_connected',
    createdAt: '2026-09-09T13:12:00.000Z',
    updatedAt: date,
  },
  {
    id: oid(3),
    companyId: first,
    conversationId: cid(3),
    reference: 'DEMO-1040',
    submissionKey: 'fixture:dastarkhwan:1040',
    customerName: 'Usman (demo)',
    customerPhone: '+92 300 000 0103',
    fulfillment: 'pickup',
    items: [
      {
        productId: pid(3),
        name: 'Beef Seekh Kebab',
        quantity: 2,
        unitPrice: 58000,
        modifiers: [],
        notes: '',
        total: 116000,
      },
    ],
    subtotal: 116000,
    deliveryFee: 0,
    total: 116000,
    currency: 'PKR',
    status: 'completed',
    syncStatus: 'not_connected',
    createdAt: '2026-09-09T12:40:00.000Z',
    updatedAt: date,
  },
  {
    id: oid(4),
    companyId: second,
    conversationId: cid(4),
    reference: 'DEMO-0207',
    submissionKey: 'fixture:bun:207',
    customerName: 'Zain (demo)',
    customerPhone: '+92 300 000 0104',
    fulfillment: 'delivery',
    address: 'Demo address · Street 8, F-7',
    zone: 'F-7',
    items: [
      {
        productId: pid(10),
        name: 'Crispy Chicken',
        quantity: 2,
        unitPrice: 62000,
        modifiers: [],
        notes: '',
        total: 124000,
      },
    ],
    subtotal: 124000,
    deliveryFee: 12000,
    total: 136000,
    currency: 'PKR',
    status: 'pending',
    syncStatus: 'not_connected',
    createdAt: '2026-09-09T13:22:00.000Z',
    updatedAt: date,
  },
];

export const seedConversations: Conversation[] = seedOrders.map((order, index) => ({
  id: order.conversationId,
  companyId: order.companyId,
  customerPhone: order.customerPhone,
  customerName: order.customerName,
  channel: 'demo',
  language: 'en',
  mode: 'bot',
  version: 4,
  updatedAt: order.createdAt,
  lastInboundAt: order.createdAt,
  cart: {
    items: order.items.map((i) => ({
      productId: i.productId,
      quantity: i.quantity,
      modifierIds: [],
      notes: i.notes,
    })),
    fulfillment: order.fulfillment,
    customerName: order.customerName,
    address: order.address,
    zone: order.zone,
    revision: 3,
    reviewedRevision: 3,
    status: 'submitted',
    orderId: order.id,
    quotedTotal: order.total,
  },
  messages: [
    {
      id: `demo-message-${index}-1`,
      role: 'customer',
      text: 'Confirm',
      createdAt: order.createdAt,
    },
    {
      id: `demo-message-${index}-2`,
      role: 'assistant',
      text: `Demo order ${order.reference} received. Awaiting restaurant acceptance.`,
      createdAt: order.createdAt,
    },
  ],
}));

export const seedTraces: Trace[] = [
  {
    id: '77777777-7777-4777-a777-777777777771',
    companyId: first,
    conversationId: cid(1),
    action: 'demo_order',
    detail: 'Fictional order loaded for exploring the dashboard. No WhatsApp messages were sent.',
    createdAt: date,
    durationMs: 0,
  },
  {
    id: '77777777-7777-4777-a777-777777777772',
    companyId: second,
    conversationId: cid(4),
    action: 'demo_order',
    detail:
      'Fictional order loaded for exploring company isolation. No integrations are connected.',
    createdAt: date,
    durationMs: 0,
  },
];
